export interface Character {
	name: string;
	value: number; // DP value
	img: string;
}

/**
 * This function filters characters based on matching points and returns a random selection
 * @param characters - The list of available characters
 * @param points - The points generated by the team selector
 * @returns Array of selected characters
 */
export const RandomCharacterPicker = (
	characters: Character[],
	points: number[]
): Character[] => {
	const selectedTeam: Character[] = [];

	// Loop through the generated points and match them to characters
	points.forEach((point) => {
		const absPoint = Math.abs(point); // Ensure we work with positive values

		// Filter characters whose value matches the generated point
		const matchingCharacters = characters.filter(
			(character) => Math.abs(character.value) === absPoint
		);

		if (matchingCharacters.length > 0) {
			// Randomly pick a character from the matching characters
			const randomIndex = Math.floor(Math.random() * matchingCharacters.length);
			selectedTeam.push(matchingCharacters[randomIndex]);
		}
	});

	return selectedTeam; // Return the selected team of characters
};
