name: Deploy GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Build and Deploy
        run: |
          cd website  # Navigate to your subfolder
          npm install  # Install dependencies
          npm run build  # Build the project
          cp -r build ../build  # Move build output to the root or another directory
          cd ..  # Go back to root
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Deploy site"
          git push origin gh-pages  # Deploy to the gh-pages branch
